# Generated by Django 4.1 on 2022-08-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messaging_config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagingmedia',
            name='parent_message',
        ),
        migrations.RemoveField(
            model_name='messagingtext',
            name='parent_message',
        ),
        migrations.DeleteModel(
            name='MessagingButtonsUser',
        ),
        migrations.DeleteModel(
            name='MessagingConfig',
        ),
        migrations.DeleteModel(
            name='MessagingMedia',
        ),
        migrations.DeleteModel(
            name='MessagingText',
        ),
    ]
