# Generated by Django 4.1 on 2022-08-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_commands_config', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandsbuttonsuser',
            name='type_button1',
            field=models.CharField(choices=[('text', 'Text button'), ('location', 'Ask location'), ('phone', 'Ask phone number')], default='text', max_length=20, verbose_name='Button №1 type'),
        ),
        migrations.AddField(
            model_name='commandsbuttonsuser',
            name='type_button2',
            field=models.CharField(choices=[('text', 'Text button'), ('location', 'Ask location'), ('phone', 'Ask phone number')], default='text', max_length=20, verbose_name='Button №1 type'),
        ),
        migrations.AddField(
            model_name='commandsbuttonsuser',
            name='type_button3',
            field=models.CharField(choices=[('text', 'Text button'), ('location', 'Ask location'), ('phone', 'Ask phone number')], default='text', max_length=20, verbose_name='Button №1 type'),
        ),
    ]
