# Generated by Django 4.1 on 2022-08-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_settings_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTelegramID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=20, verbose_name='ID')),
            ],
            options={
                'verbose_name': "Admin's telegram ID",
                'verbose_name_plural': "Admin's telegram IDs",
            },
        ),
    ]
