# Generated by Django 4.1 on 2022-08-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_settings_config', '0002_admintelegramid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botsettings',
            name='non_stop',
        ),
        migrations.AddField(
            model_name='botsettings',
            name='status',
            field=models.CharField(choices=[('enabled', 'Yes'), ('disabled', 'No')], default='disabled', max_length=30, verbose_name='Launch bot? '),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='superuser_password',
            field=models.CharField(default='#21White_Horse12#', max_length=120, verbose_name='Change superuser server password'),
        ),
    ]
