# Generated by Django 4.1 on 2022-08-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_settings_config', '0003_remove_botsettings_non_stop_botsettings_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotSettings',
        ),
    ]
