# Generated by Django 4.1 on 2022-08-20 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StepMessagingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_message', models.CharField(max_length=120, unique=True, verbose_name='After which message or command Bot should start step messaging?')),
                ('send_to_admins', models.BooleanField(default=True, verbose_name='Send user replies to admin accounts?')),
            ],
            options={
                'verbose_name': 'Step Messaging configuration',
                'verbose_name_plural': 'Step Messaging configurations',
            },
        ),
        migrations.CreateModel(
            name='StepMessagingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_messaging_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_step_messaging_config.stepmessagingconfig')),
            ],
            options={
                'verbose_name': 'Step',
                'verbose_name_plural': 'Steps',
            },
        ),
        migrations.CreateModel(
            name='StepMessagingText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Enter your text for Bot message')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_step_messaging_config.stepmessagingstep')),
            ],
            options={
                'verbose_name': "Bot's text message for replying to User",
                'verbose_name_plural': "Bot's text messages for replying to User",
            },
        ),
        migrations.CreateModel(
            name='StepMessagingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='bot-media-files', verbose_name='Add your media file to Bot message')),
                ('caption', models.TextField(blank=True, verbose_name='Caption')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_step_messaging_config.stepmessagingstep')),
            ],
            options={
                'verbose_name': 'Media file for replying to User',
                'verbose_name_plural': 'Media files for replying to User',
            },
        ),
        migrations.CreateModel(
            name='StepMessagingButtonsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_1', models.CharField(max_length=21, verbose_name='First button text')),
                ('button_2', models.CharField(blank=True, max_length=21, verbose_name='Second button text')),
                ('button_3', models.CharField(blank=True, max_length=21, verbose_name='Third button text')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_step_messaging_config.stepmessagingstep')),
            ],
            options={
                'verbose_name': 'User button for replying to Bot',
                'verbose_name_plural': 'User button for replying to Bot',
            },
        ),
    ]
