# Generated by Django 4.1 on 2022-08-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_step_messaging_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepmessagingstep',
            name='step_name',
            field=models.CharField(default='', max_length=120, verbose_name='Step name'),
        ),
    ]
