# Generated by Django 4.1 on 2022-08-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_step_messaging_config', '0002_stepmessagingstep_step_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepmessagingstep',
            name='step_name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Step name'),
        ),
    ]
