# Generated by Django 4.1 on 2022-08-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_step_messaging_config', '0003_alter_stepmessagingstep_step_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepmessagingstep',
            name='send_first',
            field=models.CharField(choices=[('text', 'Text Message'), ('media', 'Media Message')], default='text', max_length=20, verbose_name='Send first'),
        ),
    ]
