# Generated by Django 4.1 on 2022-08-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_step_messaging_config', '0004_stepmessagingstep_send_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepmessagingconfig',
            name='step_messaging_title',
            field=models.CharField(default='', max_length=120, verbose_name="Step messaging title. For example: 'Brief'"),
        ),
    ]
