# Generated by Django 4.1 on 2022-08-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_step_messaging_config', '0005_stepmessagingconfig_step_messaging_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepmessagingstep',
            name='last_step',
            field=models.BooleanField(default=False, verbose_name='Last step?'),
        ),
    ]
