# Generated by Django 4.1 on 2022-08-21 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_step_messaging_config', '0006_stepmessagingstep_last_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepmessagingstep',
            name='last_step',
        ),
    ]
