# Generated by Django 4.1 on 2022-08-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_step_messaging_config', '0007_remove_stepmessagingstep_last_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepmessagingconfig',
            name='step_messaging_title',
            field=models.CharField(max_length=120, verbose_name="Step messaging title. For example: 'Brief'"),
        ),
    ]
