# Generated by Django 4.1 on 2022-08-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_step_messaging_config', '0008_alter_stepmessagingconfig_step_messaging_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepmessagingbuttonsuser',
            name='type_button1',
            field=models.CharField(choices=[('text', 'Text button'), ('location', 'Ask location'), ('phone', 'Ask phone number')], default='text', max_length=20, verbose_name='Button №1 type'),
        ),
        migrations.AddField(
            model_name='stepmessagingbuttonsuser',
            name='type_button2',
            field=models.CharField(choices=[('text', 'Text button'), ('location', 'Ask location'), ('phone', 'Ask phone number')], default='text', max_length=20, verbose_name='Button №1 type'),
        ),
        migrations.AddField(
            model_name='stepmessagingbuttonsuser',
            name='type_button3',
            field=models.CharField(choices=[('text', 'Text button'), ('location', 'Ask location'), ('phone', 'Ask phone number')], default='text', max_length=20, verbose_name='Button №1 type'),
        ),
        migrations.AlterField(
            model_name='stepmessagingbuttonsuser',
            name='button_1',
            field=models.CharField(max_length=21, verbose_name='Button №1 text'),
        ),
        migrations.AlterField(
            model_name='stepmessagingbuttonsuser',
            name='button_2',
            field=models.CharField(blank=True, max_length=21, verbose_name='Button №2 text'),
        ),
        migrations.AlterField(
            model_name='stepmessagingbuttonsuser',
            name='button_3',
            field=models.CharField(blank=True, max_length=21, verbose_name='Button №3 text'),
        ),
    ]
