# Generated by Django 4.1 on 2022-08-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_step_messaging_config', '0010_alter_stepmessagingbuttonsuser_type_button2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepmessagingconfig',
            name='last_bot_message',
            field=models.CharField(default='', max_length=120, verbose_name='Enter the last message for user from bot, for completing step messaging'),
        ),
        migrations.AlterField(
            model_name='stepmessagingconfig',
            name='start_message',
            field=models.CharField(max_length=120, unique=True, verbose_name='After which message or command of User, Bot should start step messaging?'),
        ),
    ]
