# Generated by Django 4.1 on 2022-08-25 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_step_messaging_config', '0012_alter_stepmessagingconfig_last_bot_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastMessageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Last Message',
                'verbose_name_plural': 'Lase Messages',
            },
        ),
        migrations.RemoveField(
            model_name='stepmessagingconfig',
            name='last_bot_message',
        ),
        migrations.CreateModel(
            name='LastMessageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Enter your text for Bot message')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_step_messaging_config.lastmessageconfig')),
            ],
            options={
                'verbose_name': "Bot's text message for replying to User",
                'verbose_name_plural': "Bot's text messages for replying to User",
            },
        ),
        migrations.CreateModel(
            name='LastMessageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='bot-media-files', verbose_name='Add your media file to Bot message')),
                ('caption', models.TextField(blank=True, verbose_name='Caption')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_step_messaging_config.lastmessageconfig')),
            ],
            options={
                'verbose_name': 'Media file for replying to User',
                'verbose_name_plural': 'Media files for replying to User',
            },
        ),
        migrations.AddField(
            model_name='lastmessageconfig',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_step_messaging_config.stepmessagingconfig'),
        ),
        migrations.CreateModel(
            name='LastMessageButtonsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_1', models.CharField(max_length=21, verbose_name='Button №1 text')),
                ('type_button1', models.CharField(choices=[('text', 'Text button'), ('location', 'Ask location'), ('phone', 'Ask phone number')], default='text', max_length=20, verbose_name='Button №1 type')),
                ('button_2', models.CharField(blank=True, max_length=21, verbose_name='Button №2 text')),
                ('type_button2', models.CharField(blank=True, choices=[('text', 'Text button'), ('location', 'Ask location'), ('phone', 'Ask phone number')], default='text', max_length=20, verbose_name='Button №2 type')),
                ('button_3', models.CharField(blank=True, max_length=21, verbose_name='Button №3 text')),
                ('type_button3', models.CharField(blank=True, choices=[('text', 'Text button'), ('location', 'Ask location'), ('phone', 'Ask phone number')], default='text', max_length=20, verbose_name='Button №3 type')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_step_messaging_config.lastmessageconfig')),
            ],
            options={
                'verbose_name': 'User button for replying to Bot',
                'verbose_name_plural': 'User button for replying to Bot',
            },
        ),
    ]
