# Generated by Django 4.1 on 2022-08-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_step_messaging_config', '0013_lastmessageconfig_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lastmessageconfig',
            options={'verbose_name': 'Last Message', 'verbose_name_plural': 'Last Messages'},
        ),
        migrations.AddField(
            model_name='lastmessageconfig',
            name='send_first',
            field=models.CharField(choices=[('text', 'Text Message'), ('media', 'Media Message')], default='text', max_length=20, verbose_name='Send first'),
        ),
    ]
