# Generated by Django 4.1 on 2022-08-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_step_messaging_config', '0014_alter_lastmessageconfig_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stepmessagingconfig',
            old_name='send_to_admins',
            new_name='send_to_admin',
        ),
    ]
