# Generated by Django 4.1 on 2022-09-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_step_messaging_config', '0015_rename_send_to_admins_stepmessagingconfig_send_to_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lastmessagebuttonsuser',
            options={'verbose_name': 'User button for last message from bot', 'verbose_name_plural': 'User buttons for last message from bot'},
        ),
        migrations.AlterModelOptions(
            name='lastmessagemedia',
            options={'verbose_name': "Bot's media for last message", 'verbose_name_plural': "Bot's media for last messages"},
        ),
        migrations.AlterModelOptions(
            name='lastmessagetext',
            options={'verbose_name': "Bot's text for last message", 'verbose_name_plural': "Bot's text for last messages"},
        ),
        migrations.AlterField(
            model_name='lastmessagetext',
            name='text',
            field=models.TextField(verbose_name='Enter your text for last message in this step messaging'),
        ),
    ]
